export const STARTING_PIECE_COUNT_EASY = 3
export const STARTING_PIECE_COUNT_MEDIUM = 5
export const STARTING_PIECE_COUNT_HARD = 7

export const REMEMBER_TIME_PER_PIECE = 2500

export const TIME_AT_WHICH_TO_PLAY_TIMER_SOUND = 5000

export const WRONG_PIECES_LOSE_THRESHOLD = 20

export const LEVEL_PROGRESSION_MIN_POSITIONS = 3
export const AVERAGE_ACCURACY_PROGRESS_PERCENTAGE = 80